apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: infernal-web
  namespace: "421970311289"
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/invoker-iam-disabled: "true"

spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 421970311289-compute@developer.gserviceaccount.com

      containers:
        - image: gcr.io/421970311289/infernal-web  # 👈 YOUR BUILT IMAGE
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi

  traffic:
    - percent: 100
      latestRevision: true
