steps:
# 1. Build the backend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/m3tal-project/infernal-api', '.']

# 2. Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/m3tal-project/infernal-api']

# 3. Deploy the container to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - infernal-api
    - --image=gcr.io/m3tal-project/infernal-api
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated
    - --add-cloudsql-instances=m3tal-project:us-central1:infernal-db
    - --set-env-vars=DB_USER=m3tal,DB_PASS=inksteel,DB_NAME=infernal,DB_HOST=/cloudsql/m3tal-project:us-central1:infernal-db,ENV=production,MIGRATIONS_DIR=migrations

images:
- gcr.io/m3tal-project/infernal-api
