name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: m3tal-project
  SERVICE_NAME: infernal-web
  REGION: us-central1
  IMAGE: gcr.io/m3tal-project/infernal-web

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.IMAGE }} .
          docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}
          flags: '--allow-unauthenticated'
